server:
  port: 8080

spring:
  application:
    name: TablesReservation_Final
  datasource:
    password: Lovelace
    url: jdbc:postgresql://localhost:5432/proyectofinal
    username: ada
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      url: mongodb+srv://samdher:Samuel1909@reservationfinal.1lszqko.mongodb.net/Reservation?retryWrites=true&w=majority

application:
  security:
    jwt:
      secret-key: d5608c2a97c84dd0c0e0374ab865a131e0305df3f642ff83a03d796d748ac251
      expiration: 86400000 # a day